
import React from 'react';
import {
  MessageSquare, Calculator, Speech, History, Globe, Atom, Beaker, Leaf, BookOpen, School, DollarSign, Laptop, Palette, Music, Volleyball, Scale, Book, BookMarked, Briefcase, Award, GraduationCap, Building
} from 'lucide-react';

export const allSubjects: string[] = [
  "nederlands", "wiskunde", "engels", "geschiedenis", "aardrijkskunde",
  "natuurkunde", "scheikunde", "biologie", "frans", "duits", "latijn", "economie",
  "informatica", "kunst", "muziek", "lichamelijke_opvoeding",
  "maatschappijleer", "ckv", "algemeen"
];

export const subjectIconMap: { [key: string]: React.ElementType } = {
  "nederlands": MessageSquare,
  "wiskunde": Calculator,
  "engels": Speech,
  "geschiedenis": History,
  "aardrijkskunde": Globe,
  "natuurkunde": Atom,
  "scheikunde": Beaker,
  "biologie": Leaf,
  "frans": BookOpen,
  "duits": School,
  "latijn": BookMarked,
  "economie": DollarSign,
  "informatica": Laptop,
  "kunst": Palette,
  "muziek": Music,
  "lichamelijke_opvoeding": Volleyball,
  "maatschappijleer": Scale,
  "ckv": Palette, // CKV is culturele en KUNSTzinnige vorming
  "algemeen": Book,
  // New education levels
  "basisschool": GraduationCap,
  "basis": School,
  "mavo": School,
  "havo": School,
  "vwo": School,
  "mbo": Briefcase,
  "hbo": Building,
  "wo": GraduationCap,
  "anders": Book,
  "default": Book
};

export const subjectDisplayTranslations: { [key: string]: { [key: string]: string } } = {
  nl: {
    "nederlands": "Nederlands", "wiskunde": "Wiskunde", "engels": "Engels", "geschiedenis": "Geschiedenis", "aardrijkskunde": "Aardrijkskunde",
    "natuurkunde": "Natuurkunde", "scheikunde": "Scheikunde", "biologie": "Biologie", "frans": "Frans", "duits": "Duits", "latijn": "Latijn", "economie": "Economie",
    "informatica": "Informatica", "kunst": "Kunst", "muziek": "Muziek", "lichamelijke_opvoeding": "Lichamelijke Opvoeding",
    "maatschappijleer": "Maatschappijleer", "ckv": "CKV", "algemeen": "Algemeen",
    // New education levels
    "basisschool": "Basisschool",
    "basis": "Basis",
    "mavo": "MAVO",
    "havo": "HAVO",
    "vwo": "VWO",
    "anders": "Anders",
  },
  en: {
    "nederlands": "Dutch", "wiskunde": "Mathematics", "engels": "English", "geschiedenis": "History", "aardrijkskunde": "Geography",
    "natuurkunde": "Physics", "scheikunde": "Chemistry", "biologie": "Biology", "frans": "French", "duits": "German", "latijn": "Latin", "economie": "Economics",
    "informatica": "Computer Science", "kunst": "Art", "muziek": "Music", "lichamelijke_opvoeding": "Physical Education",
    "maatschappijleer": "Social Studies", "ckv": "CAE", "algemeen": "General",
    // New education levels
    "basisschool": "Primary School",
    "basis": "Basis",
    "mavo": "MAVO",
    "havo": "HAVO",
    "vwo": "VWO (Pre-University)",
    "anders": "Other",
  }
};

export const educationLevels: string[] = ["basisschool", "basis", "mavo", "havo", "vwo", "anders"];

export const defaultProfileImage: string = "https://picsum.photos/100/100";

export const availableThemeColors: string[] = ['emerald', 'blue', 'rose', 'purple', 'pink', 'indigo', 'teal', 'amber'];

export const availableFonts: { id: string, name: string, className: string }[] = [
    { id: 'inter', name: 'Inter', className: 'font-inter' },
    { id: 'poppins', name: 'Poppins', className: 'font-poppins' },
    { id: 'lato', name: 'Lato', className: 'font-lato' },
    { id: 'roboto-slab', name: 'Roboto Slab', className: 'font-roboto-slab' },
    { id: 'lora', name: 'Lora', className: 'font-lora' },
];

export const defaultHomeLayout: string[] = ['subjects', 'agenda', 'files'];

export const translations: { [key:string]: { [key: string]: string } } = {
  nl: {
    // Auth & General
    welcome_title: "Welkom bij Schoolmaps!",
    welcome_description: "Al je schoolzaken op één plek. Organiseer je bestanden, beheer je agenda en versnel je leerproces.",
    create_account_login_button: "Account Aanmaken / Inloggen",
    register_title: "Registreer een Account",
    login_title: "Inloggen",
    your_name: "Volledige naam",
    email_address: "E-mailadres",
    password: "Wachtwoord",
    placeholder_name: "bv. Jan Jansen",
    placeholder_email: "jouw@email.com",
    placeholder_password: "********",
    school_name: "Naam van je school",
    class_name: "Klas (bv. H4B)",
    education_level: "Onderwijsniveau",
    register_account: "Registreer Account",
    login_button: "Login",
    already_account: "Al een account? Login hier",
    no_account_register: "Nog geen account? Registreer hier",
    success_registration: "Registratie succesvol! Controleer je e-mail om je account te verifiëren.",
    success_login: "Succesvol ingelogd! Welkom terug.",
    success_logout: "Je bent uitgelogd. Tot de volgende keer!",
    confirm_logout: "Weet je zeker dat je wilt uitloggen?",
    forgot_password: "Wachtwoord vergeten?",
    password_reset_sent: "Een e-mail voor wachtwoordherstel is verzonden naar {email}. Je gegevens blijven veilig bewaard.",
    guest_fallback_name: "Gebruiker",
    default: "Standaard",

    // Email Verification
    verify_email_title: "Verifieer je e-mailadres",
    verify_email_instructions: "We hebben een verificatielink gestuurd naar {email}. Klik op de link om je account te activeren.",
    verify_email_spam_check: "Niks ontvangen? Controleer je spamfolder of vraag hieronder een nieuwe e-mail aan.",
    verify_email_continue_button: "Ik heb geverifieerd, ga verder",
    verify_email_resend_button: "Stuur opnieuw",
    sending: "Versturen...",
    email_sent: "E-mail verzonden!",
    
    // Errors
    error_fill_all_fields: "Vul alstublieft alle verplichte velden in.",
    error_fill_current_step: "Vul alstublieft alle velden in deze stap in.",
    error_select_subjects_register: "Selecteer ten minste één vak om door te gaan.",
    error_unknown: "Er is een onbekende fout opgetreden. Probeer het opnieuw.",
    error_invalid_email: "Dit is geen geldig e-mailadres. Controleer het en probeer opnieuw.",
    error_invalid_credentials: "De combinatie van e-mail en wachtwoord is onjuist.",
    error_email_in_use: "Dit e-mailadres is al in gebruik. Probeer in te loggen.",
    error_weak_password: "Je wachtwoord is te zwak. Gebruik minimaal 6 tekens.",
    error_enter_email_for_reset: "Voer je e-mailadres in om je wachtwoord te resetten.",
    error_save_settings_failed: "Opslaan van instellingen mislukt. Probeer het opnieuw.",
    error_profile_pic_upload_failed: "Uploaden van profielfoto mislukt. Probeer het opnieuw.",
    error_password_reset_failed: "Verzenden van wachtwoordherstel mislukt.",
    error_guest_action_not_allowed: "Gastgebruikers kunnen deze actie niet uitvoeren.",
    error_profile_load_failed: "Kon je profiel niet laden. Controleer je verbinding of probeer het later opnieuw.",
    error_failed_to_load_tasks: "Kon taken niet laden. Controleer je verbinding.",
    error_failed_to_load_sets: "Kon studiereeksen niet laden. Controleer je verbinding.",
    error_failed_to_load_cards: "Kon kaarten niet laden. Controleer je verbinding.",
    error_account_disabled: "Je account is gedeactiveerd door een beheerder.",
    error_reauth_failed: "Verkeerd wachtwoord. Probeer het opnieuw.",
    error_account_deletion_failed: "Account verwijderen mislukt. Probeer het later opnieuw.",

    // Account Deletion
    delete_account_section_title: "Account Verwijderen (Gevaarzone)",
    delete_account_section_description: "Deze actie is onomkeerbaar. Al je gegevens, inclusief bestanden, notities en agenda-items, worden permanent verwijderd.",
    delete_account_button: "Verwijder Mijn Account",
    reauth_modal_title: "Bevestig je identiteit",
    reauth_modal_description: "Voer je wachtwoord in om door te gaan. Dit is een veiligheidsmaatregel.",
    confirm_delete_account_button: "Ja, Verwijder Mijn Account Permanent",
    deleting_account_progress: "Account wordt verwijderd... Dit kan even duren.",
    success_account_deleted: "Je account is succesvol verwijderd. We vinden het jammer je te zien gaan.",

    // Navigation
    my_subjects: "Mijn Vakken",
    calendar: "Agenda",
    extra_tools: "Extra Tools",
    flashcards: "Flashcards",
    study_timer: "Studeertimer",
    notes: "Notities",
    todo_list: "Takenlijst",
    settings: "Instellingen",
    app_info: "App Info",
    faq: "Veelgestelde Vragen",
    logout_button: "Uitloggen",
    
    // Home & Subjects
    my_subjects_files: "Jouw School Bestanden",
    profile_incomplete_message: "Je profiel is nog niet compleet!",
    go_to_settings_message: "Ga naar Instellingen om je vakken te selecteren.",
    select_subjects: "Selecteer je vakken",
    add_custom_subject: "Voeg een eigen vak toe",
    custom_subject_placeholder: "Naam van het vak...",
    add_subject_button: "Toevoegen",
    error_subject_exists: "Dit vak bestaat al.",
    error_subject_empty: "Vaknaam mag niet leeg zijn.",
    no_files_found: "Geen bestanden gevonden in dit vak.",
    add_file_section_title: "Bestand toevoegen:",
    file_title_placeholder: "Titel (verplicht)",
    file_description_placeholder: "Beschrijving (optioneel)",
    add_file_button: "Voeg Bestand Toe",
    select_files_button: "Selecteer Bestanden",
    delete_selected_button: "Verwijder Geselecteerde",
    share_button: "Deel",
    back_to_subjects: "Terug naar Vakken",
    back_button: "Terug",
    error_enter_file_title: "Voer een titel in voor het bestand.",
    success_file_added: "Bestand succesvol toegevoegd!",
    error_select_files_delete: "Selecteer eerst bestanden om te verwijderen.",
    confirm_delete_files: "Weet je zeker dat je {count} bestand(en) wilt verwijderen?",
    success_files_deleted: "Geselecteerde bestanden succesvol verwijderd!",
    share_link_copied: "Deellink voor '{title}' gekopieerd!",
    error_copy_share_link: "Fout bij kopiëren deellink.",
    added_on: "Toegevoegd op",
    your_files_in: "Jouw bestanden in",
    your_subjects: "Jouw Vakken",
    recent_files_title: "Recente Bestanden",
    no_recent_files: "Je hebt nog geen bestanden toegevoegd.",
    todays_agenda_title: "Agenda voor Vandaag",
    no_events_today: "Geen afspraken voor vandaag. Geniet van je dag!",
    go_to_calendar: "Bekijk volledige agenda",

    // Settings
    settings_title: "Instellingen",
    profile_section: "Profiel",
    profile_picture_upload_label: "Profielfoto uploaden:",
    profile_picture_current: "Huidige profielfoto:",
    profile_picture_upload_success: "Profielfoto succesvol bijgewerkt!",
    upload_profile_picture_button: "Upload Profielfoto",
    save_profile_info_button: "Profiel Opslaan",
    success_settings_saved: "Instellingen succesvol opgeslagen!",
    choose_theme: "Kies je thema",
    font_preference: "Kies je lettertype",
    language_preference: "Taalvoorkeur",
    dutch: "Nederlands",
    english: "Engels",
    password_reset_section_title: "Wachtwoord Resetten",
    password_reset_section_description: "Klik op de knop om een wachtwoordherstele-mail te ontvangen op {email}.",
    send_reset_email_button: "Verstuur Herstel E-mail",
    settings_account_section: "Account",
    settings_appearance_section: "Weergave",
    settings_help_info_section: "Hulp & Info",
    settings_privacy_section: "Privacy",
    privacy_policy_content: "Uw privacy is belangrijk voor ons. Deze app verzamelt minimale persoonlijke gegevens om de functionaliteit te bieden. Bestanden die u uploadt, worden in uw privéopslag opgeslagen en zijn alleen voor u toegankelijk, tenzij u ze expliciet deelt.",
    version: "Versie",
    copyright: "Alle rechten voorbehouden.",
    saving: "Opslaan...",
    confirm_remove_subjects_warning: "Weet je zeker dat je deze vakken wilt deselecteren? De bijbehorende gegevens (bestanden, notities, etc.) worden niet verwijderd, maar zijn pas weer zichtbaar als je de vakken opnieuw selecteert.",
    app_offline_message: "U bent offline. Wijzigingen worden gesynchroniseerd wanneer u weer online bent.",
    app_back_online_message: "Welkom terug online! Uw gegevens worden gesynchroniseerd.",
    home_layout_title: "Startpagina Indeling Aanpassen",
    home_layout_description: "Sleep de widgets om de volgorde op je startpagina aan te passen.",
    widget_subjects: "Mijn Vakken",
    widget_agenda: "Agenda van Vandaag",
    widget_files: "Recente Bestanden",
    notifications_settings_title: "Meldingsinstellingen",
    enable_notifications: "Meldingen inschakelen",

    // Calendar
    calendar_title: "Jouw Agenda",
    add_event: "Nieuwe Afspraak",
    event_title: "Titel afspraak",
    event_description: "Beschrijving (optioneel)",
    event_type: "Type",
    event_subject: "Vak",
    select_date: "Datum",
    select_start_time: "Starttijd",
    select_end_time: "Eindtijd",
    add_event_button: "Voeg afspraak toe",
    no_events_day: "Geen afspraken voor deze dag.",
    edit_event: "Bewerken",
    delete_event_confirm: "Weet je zeker dat je '{title}' wilt verwijderen?",
    event_test: "Toets",
    event_presentation: "Presentatie",
    event_homework: "Huiswerk",
    event_oral: "Mondeling",
    event_other: "Overig",
    all_day: "Hele dag",
    today: "Vandaag",
    week_of: "Week van",
    previous_week: "Vorige",
    next_week: "Volgende",
    error_enter_event_title: "Voer een titel in voor de afspraak.",
    success_event_added: "Afspraak succesvol toegevoegd!",
    success_event_updated: "Afspraak succesvol bijgewerkt!",
    success_event_deleted: "Afspraak succesvol verwijderd!",
    all_subjects_option: "Alle Vakken",

    // Tools
    notes_title: "Notities",
    add_note_title_placeholder: "Titel notitie (verplicht)",
    add_note_content_placeholder: "Begin met typen...",
    add_note_button: "Nieuwe Notitie",
    save_note_button: "Opslaan",
    confirm_delete_note: "Weet je zeker dat je deze notitie wilt verwijderen?",
    note_added_success: "Notitie succesvol toegevoegd!",
    note_updated_success: "Notitie succesvol bijgewerkt!",
    note_deleted_success: "Notitie succesvol verwijderd!",
    error_empty_note_title: "Titel van notitie mag niet leeg zijn.",
    
    todo_list_title: "Jouw Takenlijst",
    add_task_placeholder: "Voeg een nieuwe taak toe...",
    add_task_button: "Taak Toevoegen",
    no_tasks_found: "Geen taken gevonden. Voeg er een toe!",
    task_added_success: "Taak succesvol toegevoegd!",
    task_deleted_success: "Taak succesvol verwijderd!",
    task_updated_success: "Taak succesvol bijgewerkt!",
    confirm_delete_task: "Weet je zeker dat je deze taak wilt verwijderen?",
    error_empty_task: "Taak mag niet leeg zijn.",

    flashcards_title: "Jouw Flashcards",
    add_flashcard: "Flashcard Toevoegen",
    question: "Vraag",
    answer: "Antwoord",
    add_card_button: "Kaart Toevoegen",
    next_card: "Volgende",
    prev_card: "Vorige",
    flip_card: "Omdraaien",
    no_flashcards_found: "Geen flashcards gevonden voor deze set.",
    all_cards_learned_title: "Goed bezig!",
    all_cards_learned_desc: "Je hebt alle kaarten voor nu geleerd. Reset de voortgang om opnieuw te beginnen of kies een andere methode.",
    reset_and_start_over_button: "Reset & Leer Opnieuw",
    choose_other_method_button: "Kies Andere Methode",
    confirm_delete_flashcard: "Weet je zeker dat je deze flashcard wilt verwijderen?",
    flashcard_added_success: "Flashcards succesvol toegevoegd!",
    flashcard_deleted_success: "Flashcard succesvol verwijderd!",
    error_empty_flashcard: "Vraag en antwoord mogen niet leeg zijn.",
    
    // New Flashcard Deck translations
    select_a_subject_first: "Selecteer een vak om te beginnen",
    sets_for_subject: "Studiereeksen voor {subject}",
    select_set: "Selecteer een Studiereeks",
    create_new_set: "Nieuwe Studiereeks Maken",
    set_name_placeholder: "Naam van je set (bv. Hoofdstuk 1)",
    create_set_button: "Maak Set",
    no_sets_found: "Geen studiereeksen gevonden voor dit vak.",
    confirm_delete_set: "Weet je zeker dat je de set '{name}' en alle kaarten erin wilt verwijderen?",
    set_added_success: "Set succesvol aangemaakt!",
    set_deleted_success: "Set succesvol verwijderd!",
    error_empty_set_name: "Naam van de set mag niet leeg zijn.",
    back_to_sets: "Terug naar Sets",
    back_to_subjects_selection: "Terug naar vakken",
    manage_cards: "Beheer Kaarten",
    cards_in_set: "{count} kaarten",
    add_more_rows: "Voeg 5 extra rijen toe",

    // Flashcard Study Modes & Summary
    choose_study_mode: "Kies een studiemethode",
    study_mode_learn_title: "Leren",
    study_mode_learn_desc: "Slim algoritme (SRS) om woorden in je lange-termijngeheugen te krijgen. Ideaal om écht te leren.",
    study_mode_cram_title: "Stampen",
    study_mode_cram_desc: "Ga snel door alle kaarten heen. Perfect voor een snelle herhaling vlak voor een toets.",
    study_mode_mc_title: "Meerkeuze",
    study_mode_mc_desc: "Test je kennis met automatisch gegenereerde meerkeuzevragen. Daag jezelf uit!",
    start_session: "Start Sessie",
    show_answer: "Toon Antwoord",
    feedback_again: "Opnieuw",
    feedback_good: "Goed",
    reset_srs_progress: "Leer-voortgang resetten",
    reset_srs_confirm: "Weet je zeker dat je de leervoortgang voor deze set wilt resetten? Alle kaarten worden behandeld als nieuw.",
    session_complete: "Sessie Voltooid!",
    your_score: "Jouw score: {correct} / {total}",
    well_done_message: "Goed gedaan! Blijf zo doorgaan.",
    study_again_button: "Nog een keer",
    cards_to_go: "{count} kaarten te gaan",
    
    study_timer_title: "Studeertimer",
    focus_session: "Focus",
    break_session: "Pauze",
    focus_session_complete: "Focus sessie voltooid!",
    
    // UI
    confirm_button: "Bevestigen",
    cancel_button: "Annuleren",
    close_button: "Sluiten",
    select_level: "Selecteer Niveau",
    view: "Bekijk",
    delete: "Verwijder",
    copy_link: "Kopieer Link",
    next_button: "Volgende",

    // Intro Tutorial
    intro_step1_title: "Alles op één Plek",
    intro_step1_text: "Houd al je bestanden, notities en samenvattingen georganiseerd per vak. Nooit meer zoeken naar dat ene verslag.",
    intro_step2_title: "Beheer je Tijd",
    intro_step2_text: "Mis nooit meer een deadline met een overzichtelijke agenda voor al je toetsen, huiswerk en afspraken.",
    intro_step3_title: "Studeer Slimmer",
    intro_step3_text: "Gebruik onze slimme tools zoals flashcards en de studietimer om efficiënter te leren en betere cijfers te halen.",
    intro_step4_title: "Maak het Jouw Plek",
    intro_step4_text: "Kies je eigen kleuren en lettertype om de app perfect bij jouw stijl te laten passen. Jouw school, jouw look.",
    intro_step5_title: "Klaar om te Beginnen?",
    intro_step5_text: "Transformeer je schoolleven. Maak een account aan of log in om direct aan de slag te gaan.",
    intro_finish_button: "Aan de slag!",

    // Notifications & Streak
    notifications: "Notificaties",
    notifications_title: "Notificaties",
    no_notifications: "Je hebt nog geen notificaties.",
    mark_all_as_read: "Markeer alles als gelezen",
    streak_notification: "Goed bezig! Je hebt een reeks van {count} dagen bereikt. Hou vol!",
    streak_lost_notification: "Oh nee! Je reeks van {count} dagen is verbroken. Begin vandaag een nieuwe!",
    streak_days: "{count} dagen",
    
    // Admin
    admin_dashboard: "Admin Dashboard",
    users: "Gebruikers",
    send_broadcast: "Verstuur Mededeling",
    broadcast_message_placeholder: "Typ je mededeling hier...",
    send_message_button: "Verstuur Bericht",
    broadcast_success: "Mededeling succesvol verstuurd!",
    error_broadcast_failed: "Versturen van mededeling mislukt.",
    refresh_data: "Ververs Gegevens",
    actions: "Acties",
    status: "Status",
    active: "Actief",
    disabled: "Gedeactiveerd",
    last_login: "Laatst Ingelogd",
    enable_user: "Activeer",
    disable_user: "Deactiveer",
    confirm_disable_user: "Weet je zeker dat je gebruiker {name} wilt deactiveren? Ze kunnen niet meer inloggen.",
    confirm_enable_user: "Weet je zeker dat je gebruiker {name} wilt activeren? Ze kunnen weer inloggen.",
    user_status_updated: "Gebruikersstatus succesvol bijgewerkt.",
    error_user_status_update: "Fout bij bijwerken gebruikersstatus.",
    admin_search_placeholder: "Zoek op naam of e-mail...",
  },
  en: {
    welcome_title: "Welcome to Schoolmaps!",
    welcome_description: "All your school matters in one place. Organize files, manage your calendar, and speed up your learning.",
    create_account_login_button: "Create Account / Login",
    register_title: "Register an Account",
    login_title: "Login",
    your_name: "Full Name",
    email_address: "Email Address",
    password: "Password",
    placeholder_name: "e.g. John Doe",
    placeholder_email: "your@email.com",
    placeholder_password: "********",
    school_name: "School Name",
    class_name: "Class (e.g. 10B)",
    education_level: "Education Level",
    register_account: "Register Account",
    login_button: "Login",
    already_account: "Already have an account? Login here",
    no_account_register: "No account yet? Register here",
    success_registration: "Registration successful! Please check your email to verify your account.",
    success_login: "Successfully logged in! Welcome back.",
    success_logout: "You have been logged out. See you next time!",
    confirm_logout: "Are you sure you want to log out?",
    forgot_password: "Forgot Password?",
    password_reset_sent: "A password reset email has been sent to {email}. Your data will remain safe.",
    guest_fallback_name: "User",
    default: "Default",
    
    // Email Verification
    verify_email_title: "Verify Your Email Address",
    verify_email_instructions: "We've sent a verification link to {email}. Click the link to activate your account.",
    verify_email_spam_check: "Didn't receive it? Check your spam folder or request a new email below.",
    verify_email_continue_button: "I've Verified, Continue",
    verify_email_resend_button: "Resend Email",
    sending: "Sending...",
    email_sent: "Email Sent!",

    // Errors
    error_fill_all_fields: "Please fill in all required fields.",
    error_fill_current_step: "Please fill in all fields in this step.",
    error_select_subjects_register: "Please select at least one subject to continue.",
    error_unknown: "An unknown error occurred. Please try again.",
    error_invalid_email: "This is not a valid email address. Please check and try again.",
    error_invalid_credentials: "The email and password combination is incorrect.",
    error_email_in_use: "This email address is already in use. Try logging in.",
    error_weak_password: "Your password is too weak. Please use at least 6 characters.",
    error_enter_email_for_reset: "Please enter your email address to reset your password.",
    error_save_settings_failed: "Failed to save settings. Please try again.",
    error_profile_pic_upload_failed: "Failed to upload profile picture. Please try again.",
    error_password_reset_failed: "Failed to send password reset email.",
    error_guest_action_not_allowed: "Guest users cannot perform this action.",
    error_profile_load_failed: "Could not load your profile. Check your connection or try again later.",
    error_failed_to_load_tasks: "Failed to load tasks. Please check your connection.",
    error_failed_to_load_sets: "Failed to load study sets. Please check your connection.",
    error_failed_to_load_cards: "Failed to load cards. Please check your connection.",
    error_account_disabled: "Your account has been disabled by an administrator.",
    error_reauth_failed: "Incorrect password. Please try again.",
    error_account_deletion_failed: "Failed to delete account. Please try again later.",

    // Account Deletion
    delete_account_section_title: "Delete Account (Danger Zone)",
    delete_account_section_description: "This action is irreversible. All of your data, including files, notes, and calendar events, will be permanently deleted.",
    delete_account_button: "Delete My Account",
    reauth_modal_title: "Confirm Your Identity",
    reauth_modal_description: "For your security, please enter your password to continue.",
    confirm_delete_account_button: "Yes, Delete My Account Permanently",
    deleting_account_progress: "Deleting account... This may take a moment.",
    success_account_deleted: "Your account has been successfully deleted. We're sorry to see you go.",

    my_subjects: "My Subjects",
    calendar: "Calendar",
    extra_tools: "Extra Tools",
    settings: "Settings",
    app_info: "App Info",
    faq: "FAQ",
    logout_button: "Log Out",
    select_subjects: "Select your subjects",
    add_custom_subject: "Add a custom subject",
    custom_subject_placeholder: "Name of the subject...",
    add_subject_button: "Add",
    error_subject_exists: "This subject already exists.",
    error_subject_empty: "Subject name cannot be empty.",
    settings_title: "Settings",
    profile_section: "Profile",
    save_profile_info_button: "Save Profile",
    success_settings_saved: "Settings saved successfully!",
    choose_theme: "Choose your theme",
    font_preference: "Choose your font",
    language_preference: "Language Preference",
    dutch: "Dutch",
    english: "English",
    password_reset_section_title: "Reset Password",
    password_reset_section_description: "Click the button to receive a password reset email at {email}.",
    send_reset_email_button: "Send Reset Email",
    settings_account_section: "Account",
    settings_appearance_section: "Appearance",
    settings_help_info_section: "Help & Info",
    settings_privacy_section: "Privacy",
    privacy_policy_content: "Your privacy is important to us. This application collects minimal personal data to provide its functionality. Files you upload are stored in your private storage and are only accessible by you, unless you explicitly share them.",
    version: "Version",
    copyright: "All rights reserved.",
    saving: "Saving...",
    confirm_remove_subjects_warning: "Are you sure you want to deselect these subjects? The associated data (files, notes, etc.) will not be deleted, but will only be visible again once you re-select the subjects.",
    app_offline_message: "You are offline. Changes will sync when you're back online.",
    app_back_online_message: "Welcome back online! Your data will now be synced.",
    confirm_button: "Confirm",
    cancel_button: "Cancel",
    close_button: "Close",
    select_level: "Select Level",
    next_button: "Next",
    home_layout_title: "Customize Home Page Layout",
    home_layout_description: "Drag and drop the widgets to reorder your home page.",
    widget_subjects: "My Subjects",
    widget_agenda: "Today's Agenda",
    widget_files: "Recent Files",
    notifications_settings_title: "Notification Settings",
    enable_notifications: "Enable Notifications",

    // Home
    todays_agenda_title: "Today's Agenda",
    no_events_today: "No events scheduled for today. Enjoy your day!",
    go_to_calendar: "View Full Calendar",
    
    // Timer
    study_timer_title: "Study Timer",
    focus_session: "Focus",
    break_session: "Break",
    focus_session_complete: "Focus session complete!",

    // Flashcards
    flashcards_title: "Your Flashcards",
    no_flashcards_found: "No flashcards found for this set.",
    all_cards_learned_title: "Well Done!",
    all_cards_learned_desc: "You have learned all due cards for now. Reset the progress to start over, or choose another method.",
    reset_and_start_over_button: "Reset & Learn Again",
    choose_other_method_button: "Choose Other Method",
    choose_study_mode: "Choose a Study Mode",
    study_mode_learn_title: "Learn",
    study_mode_learn_desc: "Uses a smart algorithm (SRS) to show you cards at the perfect time, building long-term memory.",
    study_mode_cram_title: "Cram",
    study_mode_cram_desc: "Quickly review all cards in the set. Perfect for last-minute revision.",
    study_mode_mc_title: "Multiple Choice",
    study_mode_mc_desc: "Test your knowledge with auto-generated multiple-choice questions. Challenge yourself!",
    start_session: "Start Session",
    show_answer: "Show Answer",
    feedback_again: "Again",
    feedback_good: "Good",
    reset_srs_progress: "Reset Learn Progress",
    reset_srs_confirm: "Are you sure you want to reset the learning progress for this set? All cards will be treated as new.",
    session_complete: "Session Complete!",
    your_score: "Your Score: {correct} / {total}",
    well_done_message: "Well done! Keep up the great work.",
    study_again_button: "Study Again",
    sets_for_subject: "Study Sets for {subject}",
    select_set: "Select a Study Set",
    create_new_set: "Create New Set",
    set_name_placeholder: "Name of your set (e.g. Chapter 1)",
    create_set_button: "Create Set",
    no_sets_found: "No sets found for this subject.",
    confirm_delete_set: "Are you sure you want to delete the set '{name}' and all cards within it?",
    set_added_success: "Set created successfully!",
    set_deleted_success: "Set deleted successfully!",
    error_empty_set_name: "Set name cannot be empty.",
    back_to_sets: "Back to Sets",
    manage_cards: "Manage Cards",
    cards_in_set: "{count} cards",

    // Intro Tutorial
    intro_step1_title: "Everything in One Place",
    intro_step1_text: "Keep all your files, notes, and summaries organized by subject. No more searching for that one report.",
    intro_step2_title: "Manage Your Time",
    intro_step2_text: "Never miss a deadline again with a clear calendar for all your tests, homework, and appointments.",
    intro_step3_title: "Study Smarter",
    intro_step3_text: "Use our smart tools like flashcards and the study timer to learn more efficiently and get better grades.",
    intro_step4_title: "Make It Your Own",
    intro_step4_text: "Choose your own colors and font to make the app perfectly match your style. Your school, your look.",
    intro_step5_title: "Ready to Start?",
    intro_step5_text: "Transform your school life. Create an account or log in to get started right away.",
    intro_finish_button: "Let's Go!",
    
    // Notifications & Streak
    notifications: "Notifications",
    notifications_title: "Notifications",
    no_notifications: "You don't have any notifications yet.",
    mark_all_as_read: "Mark all as read",
    streak_notification: "Great job! You've reached a {count}-day streak. Keep it up!",
    streak_lost_notification: "Oh no! Your {count}-day streak was broken. Start a new one today!",
    streak_days: "{count} days",
    
    // Admin
    admin_dashboard: "Admin Dashboard",
    users: "Users",
    send_broadcast: "Send Broadcast",
    broadcast_message_placeholder: "Type your message here...",
    send_message_button: "Send Message",
    broadcast_success: "Broadcast message sent successfully!",
    error_broadcast_failed: "Failed to send broadcast message.",
    refresh_data: "Refresh Data",
    actions: "Actions",
    status: "Status",
    active: "Active",
    disabled: "Disabled",
    last_login: "Last Login",
    enable_user: "Enable",
    disable_user: "Disable",
    confirm_disable_user: "Are you sure you want to disable user {name}? They will not be able to log in.",
    confirm_enable_user: "Are you sure you want to enable user {name}? They will be able to log in again.",
    user_status_updated: "User status updated successfully.",
    error_user_status_update: "Error updating user status.",
    admin_search_placeholder: "Search by name or email...",
  }
};
